- include_role:
    name: iosxe_golden_config_deploy/PRE_CHECKS

- include_role:
    name: iosxe_golden_config_deploy/BACKUP

- include_role:
    name: iosxe_golden_config_deploy/PUSH_CONFIG

- include_role:
    name: iosxe_golden_config_deploy/POST_CHECKS