- include_role:
    name: render/netbox_fetch
  
- include_role:
    name: render/build_context

- include_role:
    name: render/render_template

  loop: "{{ golden_config_devices}}"  
  loop_control:
    loop_var: device