---
- name: Render IOS-XE access-switch golden configuration
  hosts: localhost
  gather_facts: false
  
  vars_files:
  - vars/golden_config.yml

  roles:
    - role: render

- name: Deploy IOS-XE access-switch golden configuration
  hosts: iosxe_access_switches
  gather_facts: false
  connection: ansible.netcommon.network_cli
  collections:
    - cisco.ios
    - ansible.netcommon
  
  vars_files:
  - vars/golden_config.yml

  roles:
    - role: deploy
