- name: Query interfaces
  ansible.builtin.uri:
    url: "{{ netbox_api_url }}/api/dcim/interfaces/?device_id={{ golden_config_device_record.id }}&limit=200"
    method: GET
    headers: "{{ golden_config_netbox_headers }}"
    return_content: true
  register: interfaces_query
  no_log: true

- name: Query VLANs
  ansible.builtin.uri:
    url: "{{ netbox_api_url }}/api/ipam/vlans/?site_id={{ golden_config_device_record.site.id }}&limit=200"
    method: GET
    headers: "{{ golden_config_netbox_headers }}"
    return_content: true
  register: vlans_query
  no_log: true

- name: Query primary IP
  ansible.builtin.uri:
    url: "{{ netbox_api_url }}/api/ipam/ip-addresses/{{ golden_config_device_record.primary_ip4.id }}/"
    method: GET
    headers: "{{ golden_config_netbox_headers }}"
    return_content: true
  register: primary_ip4_query
  when: golden_config_device_record.primary_ip4 is defined
  no_log: true

- name: Query golden_config_device_record IPs
  ansible.builtin.uri:
    url: "{{ netbox_api_url }}/api/ipam/ip-addresses/?device_id={{ golden_config_device_record.id }}&family=4&limit=100"
    method: GET
    headers: "{{ golden_config_netbox_headers }}"
    return_content: true
  register: device_ips_query
  no_log: true

- name: Query management prefix
  ansible.builtin.uri:
    url: "{{ netbox_api_url }}/api/ipam/prefixes/?site_id={{ golden_config_device_record.site.id }}&tag=management-subnet&limit=50"
    method: GET
    headers: "{{ golden_config_netbox_headers }}"
    return_content: true
  register: mgmt_prefix_query
  no_log: true

- name: Query OOB prefix
  ansible.builtin.uri:
    url: "{{ netbox_api_url }}/api/ipam/prefixes/?site_id={{ golden_config_device_record.site.id }}&tag=oob-subnet&limit=50"
    method: GET
    headers: "{{ golden_config_netbox_headers }}"
    return_content: true
  register: oob_prefix_query
  no_log: true

- name: Build render context
  ansible.builtin.set_fact:
    render_context:
      golden_config_device_record: "{{ golden_config_device_record }}"
      interfaces: "{{ interfaces_query.json.results | default([]) }}"
      vlans: "{{ vlans_query.json.results | default([]) }}"
      primary_ip: >-
        {{
          primary_ip4_query.json
          if (golden_config_device_record.primary_ip4 is defined)
          else {}
        }}
      golden_config_device_record_ips: "{{ golden_config_device_record_ips_query.json.results | default([]) }}"
      mgmt_prefix: >-
        {{
          (mgmt_prefix_query.json.results | default([]) | first)
          | default({})
        }}
      oob_prefix: >-
        {{
          (oob_prefix_query.json.results | default([]) | first)
          | default({})
        }}
      golden_config_context: "{{ golden_config_device_record.config_context.golden_config | default({}) }}"
  no_log: true

