- include_role:
  name: netbox_golden_config_render/NETBOX_FETCH
  
- include_role:
  name: netbox_golden_config_render/BUILD_CONTEXT

- include_role:
  name: netbox_golden_config_render/RENDER_TEMPLATE